name = "your-worker-name"
main = "_worker.js"  # or _worker.js depending on your build


[build]
command = "npm run build"  # or "vite build", etc.
upload_format = "service-worker"  # or "modules"

[assets]
directory = "static"
binding = "ASSETS"